version: '3.8'

# MySQL 서버

services:
  db:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root872@
      MYSQL_DATABASE: modudoc_db
      MYSQL_USER: userTest
      MYSQL_PASSWORD: tp81w23
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: